services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: "npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./backend/app:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    command: "npm run dev"
